/**
 * Product Phase 52-B — Role-based Access Live Smoke lock SSOT.
 */
export const PHASE52B_ROLE_BASED_ACCESS_LIVE_SMOKE_LOCK_MARKER =
  "phase52b-legal-reliability-role-based-access-live-smoke-lock" as const;

export const PHASE52B_ROLE_BASED_ACCESS_LIVE_SMOKE_EVIDENCE_TAG =
  "EVIDENCE-20260525-AIBEOPCHIN-LEGAL-RELIABILITY-PHASE52B-ROLE-BASED-ACCESS-LIVE-SMOKE" as const;

export const PHASE52B_ONE_LINE_CRITERION =
  "Phase 52-B validates CLIENT, STAFF, LAWYER, and ADMIN role boundaries for Action Loop and Action Operations on staging." as const;

export const PHASE52B_REQUIRED_DENIALS = [
  "CLIENT_ROLE_OPERATION_ASSIGNMENT_FORBIDDEN",
  "CLIENT_ROLE_COMPLETION_REVIEW_FORBIDDEN",
  "CLIENT_ROLE_ACTION_OPERATION_DASHBOARD_FORBIDDEN",
  "NO_AI_COMPLETION_DECISION",
  "NO_CLIENT_ACCESS_TO_INTERNAL_ACTION_OPERATIONS",
] as const;

export const PHASE52B_LOCKED_BOUNDARIES = [
  "NO_GO_LIVE_WITHOUT_ROLE_SMOKE",
  "NO_GO_LIVE_WITH_CLIENT_INTERNAL_ACCESS",
] as const;
