/**
 * Phase 13-A — Legal Document Intelligence taskType registry SSOT.
 */
import { PHASE13A_LEGAL_DOCUMENT_INTELLIGENCE_MARKER } from "./document-intelligence-engine.schema";

export { PHASE13A_LEGAL_DOCUMENT_INTELLIGENCE_MARKER };

export const DOCUMENT_INTELLIGENCE_TASK_TYPES = {
  LEGAL_FILE_CLASSIFY: "LEGAL_FILE_CLASSIFY",
  LEGAL_TEXT_EXTRACT_VALIDATE: "LEGAL_TEXT_EXTRACT_VALIDATE",
  LEGAL_DOCUMENT_SUMMARIZE: "LEGAL_DOCUMENT_SUMMARIZE",
  OPPONENT_BRIEF_ANALYZE: "OPPONENT_BRIEF_ANALYZE",
  COURT_ORDER_ANALYZE: "COURT_ORDER_ANALYZE",
  DEADLINE_EXTRACT: "DEADLINE_EXTRACT",
  EVIDENCE_EXTRACT: "EVIDENCE_EXTRACT",
  CLAIM_EXTRACT: "CLAIM_EXTRACT",
  CLAIM_EVIDENCE_MAP: "CLAIM_EVIDENCE_MAP",
  CASE_RECORD_CONTRADICTION_SCAN: "CASE_RECORD_CONTRADICTION_SCAN",
  LAWYER_ACTION_RECOMMEND: "LAWYER_ACTION_RECOMMEND",
  CLIENT_CONFIRMATION_QUESTION_GENERATE: "CLIENT_CONFIRMATION_QUESTION_GENERATE",
  LITIGATION_DRAFT_CONTEXT_BUILD: "LITIGATION_DRAFT_CONTEXT_BUILD",
} as const;

export type DocumentIntelligenceTaskType =
  (typeof DOCUMENT_INTELLIGENCE_TASK_TYPES)[keyof typeof DOCUMENT_INTELLIGENCE_TASK_TYPES];

export const DOCUMENT_INTELLIGENCE_GOVERNANCE_FEATURE = "DOCUMENT_INTELLIGENCE" as const;

/** Phase별 taskType 그룹 (로드맵 SSOT) */
export const DOCUMENT_INTELLIGENCE_TASK_TYPES_BY_PHASE = {
  "13-B": [
    DOCUMENT_INTELLIGENCE_TASK_TYPES.LEGAL_TEXT_EXTRACT_VALIDATE,
  ],
  "13-C": [DOCUMENT_INTELLIGENCE_TASK_TYPES.LEGAL_FILE_CLASSIFY],
  "13-D": [
    DOCUMENT_INTELLIGENCE_TASK_TYPES.LEGAL_DOCUMENT_SUMMARIZE,
    DOCUMENT_INTELLIGENCE_TASK_TYPES.CLAIM_EXTRACT,
    DOCUMENT_INTELLIGENCE_TASK_TYPES.DEADLINE_EXTRACT,
  ],
  "13-E": [DOCUMENT_INTELLIGENCE_TASK_TYPES.OPPONENT_BRIEF_ANALYZE],
  "13-F": [
    DOCUMENT_INTELLIGENCE_TASK_TYPES.EVIDENCE_EXTRACT,
    DOCUMENT_INTELLIGENCE_TASK_TYPES.CLAIM_EVIDENCE_MAP,
    DOCUMENT_INTELLIGENCE_TASK_TYPES.CASE_RECORD_CONTRADICTION_SCAN,
    DOCUMENT_INTELLIGENCE_TASK_TYPES.CLIENT_CONFIRMATION_QUESTION_GENERATE,
  ],
  "13-G": [DOCUMENT_INTELLIGENCE_TASK_TYPES.LAWYER_ACTION_RECOMMEND],
  "13-H": [DOCUMENT_INTELLIGENCE_TASK_TYPES.LITIGATION_DRAFT_CONTEXT_BUILD],
} as const;

export function isDocumentIntelligenceTaskType(
  value: string,
): value is DocumentIntelligenceTaskType {
  return Object.values(DOCUMENT_INTELLIGENCE_TASK_TYPES).includes(
    value as DocumentIntelligenceTaskType,
  );
}
