/**
 * Phase 19-B — Output-path redaction registry (maps 19-A tiers → operational surfaces).
 */
import type { DataRedactionPolicyEntry } from "./data-redaction-policy.schema";
import { DATA_GOVERNANCE_REDACTION_POLICY_MARKER_PHASE19B } from "./data-redaction-policy.schema";

export const DATA_REDACTION_POLICY_REGISTRY_MARKER_PHASE19B =
  DATA_GOVERNANCE_REDACTION_POLICY_MARKER_PHASE19B;

/** Global forbidden keys — legal body · prompt · transcript raw text must not leak in ops paths. */
export const DATA_REDACTION_FORBIDDEN_RAW_KEYS = [
  "body",
  "content",
  "draftText",
  "transcriptText",
  "pagesJson",
  "analysisJson",
  "extractedText",
  "prompt",
  "integratedPrompt",
  "userInstruction",
  "documentBody",
  "noticeBody",
  "snapshotJson",
  "contentJson",
  "graphJson",
  "radarJson",
  "ledgerJson",
  "statementsJson",
  "failurePayload",
  "errorStack",
  "answersJson",
  "aiDetectedText",
  "lawyerEditedText",
] as const;

export const DATA_REDACTION_REQUIRED_OUTPUT_PATHS = [
  "AUDIT_LOG_METADATA",
  "RETRY_JOB_FAILURE_PAYLOAD",
  "EXTERNAL_MESSAGE_PAYLOAD",
  "DOCUMENT_PIPELINE_FAILURE_PAYLOAD",
  "AI_AUDIT_METADATA",
  "CASE_INTELLIGENCE_SNAPSHOT",
  "LITIGATION_EXTRACTED_TEXT",
  "VOICE_TRANSCRIPT_TEXT",
] as const;

export const DATA_REDACTION_POLICY_REGISTRY: readonly DataRedactionPolicyEntry[] = [
  {
    outputPath: "AUDIT_LOG_METADATA",
    sourcePrismaModel: "AuditLog",
    sensitivityTier: "OPERATIONS_LOG",
    surfaces: ["DISPLAY", "EXPORT", "AUDIT_PERSIST"],
    forbiddenKeyPatterns: [...DATA_REDACTION_FORBIDDEN_RAW_KEYS, "message"],
    allowedKeyAllowlist: [
      "operation",
      "taskType",
      "providerId",
      "model",
      "promptKey",
      "promptVersion",
      "generationMode",
      "guardrailPolicy",
      "guardrailPassed",
      "invokedAt",
      "skippedLlm",
      "skipReason",
      "caseId",
      "entityType",
      "entityId",
      "action",
      "failureClass",
      "circuitState",
      "metadataOnly",
      "redeliveryOfLogId",
      "containsFileAttachment",
      "portalPath",
      "documentTitle",
    ],
    maxStringLength: 500,
    notes: "AuditLog.metadata — 17-B observer source; no raw legal text in ops display/export.",
    crosswalkRef: "docs/operations/AIBEOPCHIN_OPERATIONS_OBSERVER_RUNBOOK.md",
  },
  {
    outputPath: "RETRY_JOB_FAILURE_PAYLOAD",
    sourcePrismaModel: "RetryJob",
    sensitivityTier: "OPERATIONS_LOG",
    surfaces: ["DISPLAY", "EXPORT", "OPERATIONS_PAYLOAD", "AUDIT_PERSIST"],
    forbiddenKeyPatterns: [...DATA_REDACTION_FORBIDDEN_RAW_KEYS],
    allowedKeyAllowlist: [
      "jobCode",
      "sourceType",
      "failedStage",
      "resumeFromStage",
      "providerId",
      "taskType",
      "attemptCount",
      "metadataOnly",
      "circuitState",
      "action",
    ],
    maxStringLength: 400,
    notes: "RetryJob.failurePayload — 18-A recovery; metadata-only on persist.",
    crosswalkRef: "docs/operations/AIBEOPCHIN_RETRY_JOB_RECOVERY_RUNBOOK.md",
  },
  {
    outputPath: "EXTERNAL_MESSAGE_PAYLOAD",
    sourcePrismaModel: "ExternalMessageLog",
    sensitivityTier: "OPERATIONS_LOG",
    surfaces: ["DISPLAY", "EXPORT", "OPERATIONS_PAYLOAD"],
    forbiddenKeyPatterns: [...DATA_REDACTION_FORBIDDEN_RAW_KEYS, "payload", "attachment"],
    allowedKeyAllowlist: [
      "metadataOnly",
      "portalPath",
      "documentTitle",
      "containsFileAttachment",
      "channel",
      "deliveryId",
      "redeliveryOfLogId",
      "providerMessageId",
      "processedWebhookEventIds",
      "lastProviderDeliveryStatus",
      "lastWebhookSyncedAt",
      "redeliveryEligible",
      "redeliveryBlockReason",
    ],
    maxStringLength: 300,
    notes: "ExternalMessageLog.payloadSummaryJson — 18-B metadata-only re-delivery.",
    crosswalkRef: "src/features/platform/reliability/external-message-redelivery.schema.ts",
  },
  {
    outputPath: "DOCUMENT_PIPELINE_FAILURE_PAYLOAD",
    sourcePrismaModel: "DocumentPipelineJob",
    sensitivityTier: "OPERATIONS_LOG",
    surfaces: ["DISPLAY", "EXPORT", "OPERATIONS_PAYLOAD"],
    forbiddenKeyPatterns: [...DATA_REDACTION_FORBIDDEN_RAW_KEYS],
    allowedKeyAllowlist: [
      "uploadedFileId",
      "failedStage",
      "resumeFromStage",
      "completedStages",
      "duplicateGuard",
      "noReupload",
      "metadataOnly",
    ],
    maxStringLength: 400,
    notes: "DocumentPipelineJob.failurePayload — 18-C stage-preserving recovery.",
    crosswalkRef: "docs/operations/AIBEOPCHIN_DOCUMENT_PIPELINE_RECOVERY_RUNBOOK.md",
  },
  {
    outputPath: "AI_AUDIT_METADATA",
    sourcePrismaModel: "AuditLog",
    sensitivityTier: "AI_METADATA",
    surfaces: ["DISPLAY", "EXPORT", "AUDIT_PERSIST"],
    forbiddenKeyPatterns: [...DATA_REDACTION_FORBIDDEN_RAW_KEYS, "guardrailIssues"],
    allowedKeyAllowlist: [
      "operation",
      "taskType",
      "providerId",
      "model",
      "promptKey",
      "promptVersion",
      "templateAiPromptKey",
      "generationMode",
      "guardrailPolicy",
      "guardrailPassed",
      "invokedAt",
      "skippedLlm",
      "skipReason",
      "caseSummaryAiMode",
      "gongbuhoResolutionVia",
      "fallbackStrategy",
      "failureClass",
      "circuitState",
      "metadataOnly",
    ],
    maxStringLength: 300,
    notes: "AI Core / Case Summary / 18-D fallback audit metadata — public-safe strip + redaction.",
    crosswalkRef: "src/features/ai-core/ai-audit.ts",
  },
  {
    outputPath: "CASE_INTELLIGENCE_SNAPSHOT",
    sourcePrismaModel: "CaseIntelligenceSnapshot",
    sensitivityTier: "LEGAL_SENSITIVE",
    surfaces: ["DISPLAY", "EXPORT"],
    forbiddenKeyPatterns: [...DATA_REDACTION_FORBIDDEN_RAW_KEYS],
    contentFieldPaths: ["contentJson", "graphJson", "radarJson", "ledgerJson"],
    maxStringLength: 200,
    notes: "CaseIntelligenceSnapshot summary fields — ops/export only; legal workspace uses 10-C filter.",
    crosswalkRef: "src/features/ai-core/client-safe-disclosure.schema.ts",
  },
  {
    outputPath: "LITIGATION_EXTRACTED_TEXT",
    sourcePrismaModel: "LitigationExtractedText",
    sensitivityTier: "LEGAL_SENSITIVE",
    surfaces: ["EXPORT"],
    forbiddenKeyPatterns: ["pagesJson", "text", "content", "body"],
    contentFieldPaths: ["pages", "pagesJson"],
    maxStringLength: 120,
    notes: "OCR raw text — export redaction; authorized legal workspace read unchanged.",
  },
  {
    outputPath: "VOICE_TRANSCRIPT_TEXT",
    sourcePrismaModel: "VoiceTranscript",
    sensitivityTier: "LEGAL_SENSITIVE",
    surfaces: ["DISPLAY", "EXPORT"],
    forbiddenKeyPatterns: ["draftText", "transcriptText", "body", "content"],
    contentFieldPaths: ["draftText"],
    notes: "Voice transcript body — never in ops API; Voice 5-I body logging forbidden.",
    crosswalkRef: "src/lib/voice/voice-transcript-policy.ts",
  },
] as const;

export function getDataRedactionPolicyEntry(
  outputPath: DataRedactionPolicyEntry["outputPath"],
): DataRedactionPolicyEntry | undefined {
  return DATA_REDACTION_POLICY_REGISTRY.find((entry) => entry.outputPath === outputPath);
}
