/**
 * Phase 19-A — Data retention policy registry (constitution SSOT).
 * @see docs/platform/AIBEOPCHIN_DATA_GOVERNANCE_PHASE19_ROADMAP.md
 */
import type { DataRetentionPolicyEntry } from "./data-retention-policy.schema";
import { DATA_GOVERNANCE_RETENTION_CONSTITUTION_MARKER_PHASE19A } from "./data-retention-policy.schema";

export const DATA_RETENTION_POLICY_REGISTRY_MARKER_PHASE19A =
  DATA_GOVERNANCE_RETENTION_CONSTITUTION_MARKER_PHASE19A;

/** Anchor models that MUST appear in registry before any purge/redaction phase ships. */
export const DATA_RETENTION_REQUIRED_PRISMA_MODELS = [
  "Case",
  "Interview",
  "VoiceTranscript",
  "LegalDocument",
  "LitigationUploadedFile",
  "LitigationExtractedText",
  "LitigationDocumentAnalysis",
  "CaseIntelligenceSnapshot",
  "CaseClientDisclosureRelease",
  "CaseConversationMessage",
  "CasePackageShare",
  "CaseSharedDocument",
  "CaseDocumentDelivery",
  "AuditLog",
  "ExternalMessageLog",
  "CronJobExecutionLog",
  "RetryJob",
  "DocumentPipelineJob",
  "SupplementRequestAuditLog",
  "VoicePrivacyOpsRequest",
] as const;

export const DATA_RETENTION_POLICY_REGISTRY: readonly DataRetentionPolicyEntry[] = [
  {
    prismaModel: "Case",
    domain: "CASE_CORE",
    sensitivityTier: "PII",
    disposition: "RETAIN_CASE_LIFECYCLE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "사건 마스터 — legal hold default. Purge requires case closure workflow (19-E).",
  },
  {
    prismaModel: "Interview",
    domain: "CASE_CORE",
    sensitivityTier: "PII",
    disposition: "RETAIN_CASE_LIFECYCLE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "answersJson — interview PII tied to case lifecycle.",
  },
  {
    prismaModel: "VoiceTranscript",
    domain: "INTERVIEW_VOICE",
    sensitivityTier: "LEGAL_SENSITIVE",
    disposition: "RETAIN_UNTIL_EXPIRY",
    defaultRetentionDays: 3,
    purgeEligible: true,
    legalHoldDefault: false,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "Draft TTL 72h; CONFIRMED retained — crosswalk Voice 5-I.",
    crosswalkRef: "src/lib/voice/voice-transcript-policy.ts",
  },
  {
    prismaModel: "VoicePrivacyOpsRequest",
    domain: "INTERVIEW_VOICE",
    sensitivityTier: "PII",
    disposition: "RETAIN_FIXED_DAYS",
    defaultRetentionDays: 365,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "Privacy ops ticket — retain for compliance audit trail.",
    crosswalkRef: "docs/voice/VOICE_PRIVACY_RETENTION_RUNBOOK.md",
  },
  {
    prismaModel: "LegalDocument",
    domain: "LEGAL_DOCUMENT",
    sensitivityTier: "LEGAL_SENSITIVE",
    disposition: "RETAIN_CASE_LIFECYCLE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "Generated legal document — lawyer review lock applies.",
  },
  {
    prismaModel: "LitigationUploadedFile",
    domain: "DOCUMENT_INTELLIGENCE",
    sensitivityTier: "LEGAL_SENSITIVE",
    disposition: "RETAIN_CASE_LIFECYCLE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "Original blob reference — attachment lifecycle in 19-D.",
  },
  {
    prismaModel: "LitigationExtractedText",
    domain: "DOCUMENT_INTELLIGENCE",
    sensitivityTier: "LEGAL_SENSITIVE",
    disposition: "RETAIN_CASE_LIFECYCLE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "OCR/extract full text — highest sensitivity; redaction before export.",
  },
  {
    prismaModel: "LitigationDocumentAnalysis",
    domain: "DOCUMENT_INTELLIGENCE",
    sensitivityTier: "LEGAL_SENSITIVE",
    disposition: "RETAIN_CASE_LIFECYCLE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "analysisJson — lawyer review lock; no auto re-analysis (18-C).",
  },
  {
    prismaModel: "LitigationOpponentBriefAnalysis",
    domain: "DOCUMENT_INTELLIGENCE",
    sensitivityTier: "LEGAL_SENSITIVE",
    disposition: "RETAIN_CASE_LIFECYCLE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "Opponent brief analysis — manual review before client exposure.",
  },
  {
    prismaModel: "CaseIntelligenceSnapshot",
    domain: "AI_GOVERNANCE",
    sensitivityTier: "LEGAL_SENSITIVE",
    disposition: "RETAIN_CASE_LIFECYCLE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "Graph/radar/ledger JSON — client-safe filter (10-C) on exposure only.",
    crosswalkRef: "src/features/ai-core/client-safe-disclosure.schema.ts",
  },
  {
    prismaModel: "CaseClientDisclosureRelease",
    domain: "CLIENT_PORTAL",
    sensitivityTier: "LEGAL_SENSITIVE",
    disposition: "RETAIN_INDEFINITE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "Released statements audit — immutable release record.",
    crosswalkRef: "docs/ai/AIBEOPCHIN_CLIENT_SAFE_DISCLOSURE_LAYER_SPEC.md",
  },
  {
    prismaModel: "CaseConversationMessage",
    domain: "CLIENT_PORTAL",
    sensitivityTier: "PII",
    disposition: "RETAIN_CASE_LIFECYCLE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "Case-scoped messaging body — PII in thread text.",
  },
  {
    prismaModel: "CasePackageShare",
    domain: "CLIENT_PORTAL",
    sensitivityTier: "PII",
    disposition: "RETAIN_UNTIL_EXPIRY",
    defaultRetentionDays: null,
    purgeEligible: true,
    legalHoldDefault: false,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "snapshotJson — expiresAt driven; IP mask on access logs.",
    crosswalkRef: "src/features/case-package/case-package-privacy-security-policy.ts",
  },
  {
    prismaModel: "CaseSharedDocument",
    domain: "CLIENT_PORTAL",
    sensitivityTier: "LEGAL_SENSITIVE",
    disposition: "RETAIN_UNTIL_EXPIRY",
    defaultRetentionDays: null,
    purgeEligible: true,
    legalHoldDefault: false,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "Client portal share — expiresAt field; delivery in CaseDocumentDelivery.",
    crosswalkRef: "src/features/secure-document-delivery/secure-document-delivery.schema.ts",
  },
  {
    prismaModel: "CaseDocumentDelivery",
    domain: "CLIENT_PORTAL",
    sensitivityTier: "INTERNAL",
    disposition: "RETAIN_UNTIL_EXPIRY",
    defaultRetentionDays: null,
    purgeEligible: true,
    legalHoldDefault: false,
    redactionRequired: false,
    exportRedactionRequired: true,
    notes: "Secure link token hash — tokenExpiresAt; metadata-only external channel.",
    crosswalkRef: "docs/operations/AIBEOPCHIN_EXTERNAL_MESSAGE_REDELIVERY_RUNBOOK.md",
  },
  {
    prismaModel: "AuditLog",
    domain: "AUDIT_COMPLIANCE",
    sensitivityTier: "OPERATIONS_LOG",
    disposition: "PURGE_AFTER_RETENTION",
    defaultRetentionDays: 730,
    purgeEligible: true,
    legalHoldDefault: false,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "Platform audit — metadata PII gate in 19-C; 17-B observer source.",
    crosswalkRef: "docs/operations/AIBEOPCHIN_OPERATIONS_OBSERVER_RUNBOOK.md",
  },
  {
    prismaModel: "SupplementRequestAuditLog",
    domain: "AUDIT_COMPLIANCE",
    sensitivityTier: "PII",
    disposition: "RETAIN_CASE_LIFECYCLE",
    defaultRetentionDays: null,
    purgeEligible: false,
    legalHoldDefault: true,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "actionPayloadMasked pattern — masked payload SSOT for supplement domain.",
  },
  {
    prismaModel: "ExternalMessageLog",
    domain: "OPERATIONS_RELIABILITY",
    sensitivityTier: "OPERATIONS_LOG",
    disposition: "PURGE_AFTER_RETENTION",
    defaultRetentionDays: 180,
    purgeEligible: true,
    legalHoldDefault: false,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "metadata-only payloadSummaryJson — 18-B redelivery linkage.",
    crosswalkRef: "src/features/platform/reliability/external-message-redelivery.schema.ts",
  },
  {
    prismaModel: "CronJobExecutionLog",
    domain: "OPERATIONS_RELIABILITY",
    sensitivityTier: "OPERATIONS_LOG",
    disposition: "PURGE_AFTER_RETENTION",
    defaultRetentionDays: 90,
    purgeEligible: true,
    legalHoldDefault: false,
    redactionRequired: false,
    exportRedactionRequired: true,
    notes: "Cron failure triage — 18-A sync to RetryJob; errorStack may contain secrets.",
  },
  {
    prismaModel: "RetryJob",
    domain: "OPERATIONS_RELIABILITY",
    sensitivityTier: "OPERATIONS_LOG",
    disposition: "PURGE_AFTER_RETENTION",
    defaultRetentionDays: 180,
    purgeEligible: true,
    legalHoldDefault: false,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "failurePayload may contain PII — redact before export (19-B).",
    crosswalkRef: "docs/operations/AIBEOPCHIN_RETRY_JOB_RECOVERY_RUNBOOK.md",
  },
  {
    prismaModel: "DocumentPipelineJob",
    domain: "OPERATIONS_RELIABILITY",
    sensitivityTier: "OPERATIONS_LOG",
    disposition: "PURGE_AFTER_RETENTION",
    defaultRetentionDays: 180,
    purgeEligible: true,
    legalHoldDefault: false,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "18-C recovery state — no re-upload; failurePayload redaction in 19-B.",
    crosswalkRef: "docs/operations/AIBEOPCHIN_DOCUMENT_PIPELINE_RECOVERY_RUNBOOK.md",
  },
  {
    prismaModel: "VoiceInteractionTrace",
    domain: "AI_GOVERNANCE",
    sensitivityTier: "AI_METADATA",
    disposition: "PURGE_AFTER_RETENTION",
    defaultRetentionDays: 90,
    purgeEligible: true,
    legalHoldDefault: false,
    redactionRequired: true,
    exportRedactionRequired: true,
    notes: "AI metadata only — no transcript body in trace (Voice 5-I).",
    crosswalkRef: "src/lib/voice/voice-transcript-policy.ts",
  },
] as const;

export function getDataRetentionPolicyEntry(
  prismaModel: string,
): DataRetentionPolicyEntry | undefined {
  return DATA_RETENTION_POLICY_REGISTRY.find((entry) => entry.prismaModel === prismaModel);
}

export function listDataRetentionPolicyModels(): string[] {
  return DATA_RETENTION_POLICY_REGISTRY.map((entry) => entry.prismaModel);
}
