export const GONGBUHO_AUDIT_EVENTS = [
  "GONGBUHO_PACKET_CREATED",
  "GONGBUHO_PACKET_APPROVED",
  "GONGBUHO_PACKET_ARCHIVED",
  "GONGBUHO_QUESTION_SET_PROJECTED",
  "GONGBUHO_APPLIED_TO_CASE",
  "GONGBUHO_INTERVIEW_BOUND",
  "GONGBUHO_DOCUMENT_RULES_APPLIED",
  "GONGBUHO_LEGAL_KNOWLEDGE_RESEARCH_BRIEF_CREATED",
  "GONGBUHO_LEGAL_KNOWLEDGE_RESEARCH_BRIEF_READY",
  "GONGBUHO_LEGAL_KNOWLEDGE_LAWYER_REVIEW_RECORDED",
  "GONGBUHO_LEGAL_KNOWLEDGE_PACKET_DRAFT_FROM_PIPELINE",
  "GONGBUHO_LEGAL_KNOWLEDGE_PIPELINE_COMPLETED",
] as const;

export type GongbuhoAuditEvent = (typeof GONGBUHO_AUDIT_EVENTS)[number];

export const AUDIT_LOG_EVENTS: GongbuhoAuditEvent[] = [
  "GONGBUHO_PACKET_CREATED",
  "GONGBUHO_PACKET_APPROVED",
  "GONGBUHO_PACKET_ARCHIVED",
  "GONGBUHO_QUESTION_SET_PROJECTED",
  "GONGBUHO_LEGAL_KNOWLEDGE_RESEARCH_BRIEF_CREATED",
  "GONGBUHO_LEGAL_KNOWLEDGE_RESEARCH_BRIEF_READY",
  "GONGBUHO_LEGAL_KNOWLEDGE_LAWYER_REVIEW_RECORDED",
  "GONGBUHO_LEGAL_KNOWLEDGE_PACKET_DRAFT_FROM_PIPELINE",
  "GONGBUHO_LEGAL_KNOWLEDGE_PIPELINE_COMPLETED",
];

export const GONGBUHO_TRACE_EVENTS: GongbuhoAuditEvent[] = [
  "GONGBUHO_APPLIED_TO_CASE",
  "GONGBUHO_INTERVIEW_BOUND",
  "GONGBUHO_DOCUMENT_RULES_APPLIED",
];

export function isAuditLogEvent(event: GongbuhoAuditEvent): boolean {
  return AUDIT_LOG_EVENTS.includes(event);
}

export function isGongbuhoTraceEvent(event: GongbuhoAuditEvent): boolean {
  return GONGBUHO_TRACE_EVENTS.includes(event);
}
